---
- name: check for nftables pkg and install if not found
  community.general.pacman:
    name: "{{ firewall_pkg }}"
    state: present

- name: deploy nftables ruleset
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
    backup: true
  notify: restart nftables

- name: Enable nftables at boot
  ansible.builtin.service:
    name: nftables
    enabled: true
