---
default_shell: /bin/bash

#USERS

users:
  - username: alex
    groups:
      - sudo
      - devops
      - sshusers
    ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present

  - username: deploy
    groups:
      - devops
      - sshusers
    ssh_key: ""
    state: present

  - username: monitoring
    groups:
      - logging
    ssh_key: ""
    state: present

#GROUPS

custom_groups:
  - sudo
  - devops
  - sshusers
  - logging

#SUDO

sudo_password_tries: 3
sudo_badpass_message: "Womp, Womp try again"
sudo_log_dir: /var/log/sudo
sudo_require_tty: true

#PASSWORD POLICY

pass_max_days: 30
pass_min_days: 2
pass_warn_days: 7
pass_min_len: 10
pass_max_repeat: 3
pass_min_diff: 7
